---
- hosts: app
  remote_user: root

  vars:
    app_path: /root/sample-app/server-setup/rest.init.sh

  tasks:
  - name: restart rest app
    command: nohup sh "{{ app_path }}" restart
    tags:
    - snapshot
    - backup

#
# [EOF]
#
