---
- include: create_sample_vm.yml target=dbs
- include: create_sample_vm.yml target=app
- include: create_sample_vm.yml target=web
- include: create_sample_vm.yml target=web
- include: create_sample_vm.yml target=web
- include: create_sample_vm.yml target=web
- include: create_sample_vm.yml target=lbs
