---
- name: ansible_python_interpreter setup
  set_fact: ansible_python_interpreter="{{ lookup('pipe', 'which python') }}"
- name: get uuid for generate hostname
  command: /usr/bin/uuidgen
  register: result_uuid
  when: target in ["lbs", "web", "app", "dbs"]
- name: create {{ target }}-server on nova-compute
  nova_compute:
    state: present
    auth_url: "{{ auth.url }}"
    region_name: "{{ auth.region_name }}"
    login_tenant_name: "{{ auth.tenant_name }}"
    login_username: "{{ auth.username }}"
    login_password: "{{ auth.password }}"
    availability_zone: "{{ spec[target].availability_zone }}"
    flavor_ram: "{{ spec[target].flavor_ram }}"
    flavor_include: "{{ spec[target].flavor_name }}"
    floating_ip_pools: "{{ floating_ip_pool_map[spec[target].floating_ip] }}"
    image_name: "{{ spec[target].image_name }}"
    key_name: "{{  spec[target].key_name }}"
    name: "{{ target }}-{{ item }}-{{ result_uuid.stdout }}"
    nics: "{{ spec[target].networks }}"
    security_groups: "{{ spec[target].secgroups }}"
  when: (target in ["lbs", "web","app","dbs"])
  with_sequence: count="{{ instance_counts[target] }}"
